### ISSUE TITLE
Lacking Flash/Actionscript

### ISSUE THREAD

**Issue by blister** [NARKOZ/guides#3]
I know Flash isn't the new hotness anymore, but my team still needs to support several Flash-based game products. I've been on the lookout for a good style guide that is geared towards team-based Flash development, but haven't come across anything yet.

If anyone knows of a good one, I think it should be included in this list.

**Comment by NARKOZ** [comment]
http://boulderapps.co/style-guide-best-practices-for-actionscript-3-as3
